### ISSUE TITLE
No sound transmitter from one client to another, strange server code seems to be the culprit

### ISSUE THREAD

**Issue by romlel** [adrenak/univoice-telepathy-network#1]
Hello

I was testing Univoice with telepathy for a remote play application. Very good asset but I had problems going from the PUN sample to the telepathy one.

When I was recording on one client, another client could not hear it.
I saw this code snippet on the server side, and I tried a modification that seems to fix the problem

`  void OnData_Server(int sender, ArraySegment<byte> data) {
            var packet = new BytesReader(data.Array);
            var tag = packet.ReadString();

            if (tag.Equals(AUDIO_SEGMENT)) {
                var audioSender = packet.ReadShort();
                var recipient = packet.ReadShort();
                var segmentBytes = packet.ReadByteArray();

                if (recipient == OwnID)
                {
                    var segment = FromByteArray<ChatroomAudioSegment>(segmentBytes);
                    OnAudioReceived?.Invoke(audioSender, segment);
                }
                else if (PeerIDs.Contains(recipient))
                {
                    server.Send(recipient, data);                                   //"fix" code
                    //server.Send(recipient, new ArraySegment<byte>(segmentBytes)); //original code 
                }
            }
        }`

As you see on the last 2 lines, in the original code, the AUDIO_SEGMENT "packet" that is well bounced by the server from one client to another, but the data was stripped from its headers (tag , sender, recipient)...
On the receiving end, the data was missing the tag notably, and thus was not processed at all !
I changed the code making it "bounce" the full data instead of just the inner payload, and it seems to fix the problem

Can you please confirm that is indeed what happened and that my fix is sound ?
Thanks

**Comment by adrenak** [comment]
Thanks @romlel this is a bad bug I must admit. Looks like this got in because I must have tested only with one client. Fixing this now

**Comment by adrenak** [comment]
This has been fixed now on v1.0.1 thank you for the help!
